In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import linear_model

In [2]:
data = {'area':[2600,3000,3200,3600,4000],'bedrooms':[3.0,4.0,np.nan,3.0,5.0],'age':[20,15,18,30,8],'price':[550000,565000,610000,595000,760000]}

In [3]:
d = pd.DataFrame(data)
d

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
d['bedrooms'].median()

3.5

In [5]:
import math
median_bedrooms = math.floor(d['bedrooms'].median())
median_bedrooms

3

In [6]:
d.bedrooms=d.bedrooms.fillna(median_bedrooms)

In [7]:
d

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
reg = linear_model.LinearRegression() ## y =m1 x1 + m2 x2 +m3 x3 + b
reg.fit(d[['area','bedrooms','age']],d.price)

LinearRegression()

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383724.99999999994

In [11]:
reg.predict([[3000,3,40]])

array([444400.])

In [12]:
reg.predict([[3000,3,15]])

array([615025.])